# Generated by Django 4.1.7 on 2023-03-01 11:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myabout',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mycontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('zip', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
