# Generated by Django 4.1.7 on 2023-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mypost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='userid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
