# Generated by Django 4.1.7 on 2023-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mypost_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='myRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
            ],
        ),
    ]
