# Generated by Django 4.1.7 on 2023-03-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_myregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myregister',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='myregister',
            old_name='location',
            new_name='userlocation',
        ),
        migrations.RenameField(
            model_name='myregister',
            old_name='password',
            new_name='userpassword',
        ),
    ]
