# Generated by Django 4.1.7 on 2023-03-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_email_myregister_useremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myregister',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='myregister',
            old_name='userlocation',
            new_name='user_location',
        ),
        migrations.RenameField(
            model_name='myregister',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='myregister',
            old_name='userpassword',
            new_name='user_password',
        ),
    ]
