# Generated by Django 4.1.7 on 2023-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_useremail_myregister_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myregister',
            name='user_number',
            field=models.IntegerField(default=987654321),
        ),
        migrations.AlterField(
            model_name='myregister',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
