# Generated by Django 4.1.7 on 2023-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myregister_user_number_alter_myregister_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myregister',
            name='user_number',
            field=models.IntegerField(default=9876543210),
        ),
    ]
