# Generated by Django 4.1.7 on 2023-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_myabout_extra_myregister_user_multiple_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myregister',
            name='user_number',
            field=models.IntegerField(null=True),
        ),
    ]
