# Generated by Django 4.1.7 on 2023-03-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_myregister_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_images',
            name='name',
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='image',
            field=models.ImageField(upload_to='myimg'),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.mypost'),
        ),
    ]
